version: '3.6'

services:

# Database storage
  postgres:
    container_name: postgres_song_service
    image: postgres:14
    volumes:
      - "postgres-song-service-vol:/var/lib/postgresql/data"
      - "./docker-compose/postgres:/docker-entrypoint-initdb.d/"

    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - resource-network


volumes:
  postgres-song-service-vol:
    driver: local

networks:
  resource-network:
    external: true
    driver: bridge