version: '3.6'

services:

# Database storage
  postgres-songs:
    image: postgres:14
    volumes:
      - "postgres-song-service-vol:/var/lib/postgresql/data"
      - "./docker-compose/postgres:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - resource-network

  songs-service:
    image: songs-service-local-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres-songs
    networks:
      - resource-network


volumes:
  postgres-song-service-vol:
    driver: local

networks:
  resource-network:
    external: true
    driver: bridge