version: '3.6'

services:

# Database storage
  postgres:
    image: postgres:14
    volumes:
      - "postgres-data-vol:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d/"

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres-data-vol:
    driver: local
  localstack-vol: